<a href="https://colab.research.google.com/github/Ashwinikh297/R.Discriptive-Statistics/blob/main/Practice_on_EDA_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Label Encoder

In [5]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [6]:
data=pd.read_csv('https://raw.githubusercontent.com/slmsshk/DataSet/main/iris.csv')

In [8]:
data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [10]:
# changes does not effect on "data" dataframe
data1=data.copy()

In [12]:
labelencoder =LabelEncoder()
data1.iloc[:,-1]=labelencoder.fit_transform(data.iloc[:,-1])

In [14]:
data1.iloc[:,-1]

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

##One Hot Encoder

In [16]:
#using sklearn 
from sklearn.preprocessing import OneHotEncoder

In [18]:
data2= pd.read_csv('https://raw.githubusercontent.com/slmsshk/DataSet/main/iris.csv')

In [20]:
data2

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [22]:
# ceating instance of one hot encoder 
OHE= OneHotEncoder(handle_unknown='ignore')

In [25]:
# Passing Bridge_Type_cat_Column
enc_df=pd.DataFrame(OHE.fit_transform(data2[['Species']]).toarray())

In [28]:
OHE.fit_transform(data2[['Species']]).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [30]:
enc_df

       0    1    2
0    1.0  0.0  0.0
1    1.0  0.0  0.0
2    1.0  0.0  0.0
3    1.0  0.0  0.0
4    1.0  0.0  0.0
..   ...  ...  ...
145  0.0  0.0  1.0
146  0.0  0.0  1.0
147  0.0  0.0  1.0
148  0.0  0.0  1.0
149  0.0  0.0  1.0

[150 rows x 3 columns]

In [35]:
# merge with main df
data_final=data2.iloc[:,0:4].join(enc_df)
data_final

     Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    0    1    2
0             5.1          3.5           1.4          0.2  1.0  0.0  0.0
1             4.9          3.0           1.4          0.2  1.0  0.0  0.0
2             4.7          3.2           1.3          0.2  1.0  0.0  0.0
3             4.6          3.1           1.5          0.2  1.0  0.0  0.0
4             5.0          3.6           1.4          0.2  1.0  0.0  0.0
..            ...          ...           ...          ...  ...  ...  ...
145           6.7          3.0           5.2          2.3  0.0  0.0  1.0
146           6.3          2.5           5.0          1.9  0.0  0.0  1.0
147           6.5          3.0           5.2          2.0  0.0  0.0  1.0
148           6.2          3.4           5.4          2.3  0.0  0.0  1.0
149           5.9          3.0           5.1          1.8  0.0  0.0  1.0

[150 rows x 7 columns]

##PPS score

In [1]:
# installing packages
!pip install ppscore

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: ppscore in /usr/local/lib/python3.7/dist-packages (1.2.0)
Requirement already satisfied: scikit-learn<1.0.0,>=0.20.2 in /usr/local/lib/python3.7/dist-packages (from ppscore) (0.24.2)
Requirement already satisfied: pandas<2.0.0,>=1.0.0 in /usr/local/lib/python3.7/dist-packages (from ppscore) (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas<2.0.0,>=1.0.0->ppscore) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas<2.0.0,>=1.0.0->ppscore) (1.15.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (3.1.0)
Requirement already satisfied: scipy>=0.19.1 in /usr/local/lib/python3.7/dist-packages (from scikit-learn<1.0.0,>=0.20.2->ppscore) (1.7.3)

In [3]:
import ppscore as pps

In [8]:
data.head()

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
# pps.score(df,"feature_column","target_column")....# syntax

pps.score(data,"Sepal.Length", "Petal.Length")

{'x': 'Sepal.Length',
 'y': 'Petal.Length',
 'ppscore': 0.550422595049248,
 'case': 'regression',
 'is_valid_score': True,
 'metric': 'mean absolute error',
 'baseline_score': 1.4886666666666668,
 'model_score': 0.6692708968366863,
 'model': DecisionTreeRegressor()}

In [14]:
# Calculate hole pps metrix
pps.matrix(data)

,x,y,ppscore,case,is_valid_score,metric,baseline_score,model_score,model
0,Sepal.Length,Sepal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
1,Sepal.Length,Sepal.Width,0.000000,regression,True,mean absolute error,0.330667,0.364704,DecisionTreeRegressor()
2,Sepal.Length,Petal.Length,0.550423,regression,True,mean absolute error,1.488667,0.669271,DecisionTreeRegressor()
3,Sepal.Length,Petal.Width,0.431739,regression,True,mean absolute error,0.644667,0.366339,DecisionTreeRegressor()
4,Sepal.Length,Species,0.471649,classification,True,weighted F1,0.353333,0.658333,DecisionTreeClassifier()
5,Sepal.Width,Sepal.Length,0.006966,regression,True,mean absolute error,0.684667,0.679897,DecisionTreeRegressor()
6,Sepal.Width,Sepal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
7,Sepal.Width,Petal.Length,0.172375,regression,True,mean absolute error,1.488667,1.232058,DecisionTreeRegressor()
8,Sepal.Width,Petal.Width,0.132858,regression,True,mean absolute error,0.644667,0.559017,DecisionTreeRegressor()
9,Sepal.Width,Species,0.156915,classification,True,weighted F1,0.353333,0.454805,DecisionTreeClassifier()
10,Petal.Length,Sepal.Length,0.525617,regression,True,mean absolute error,0.684667,0.324794,DecisionTreeRegressor()
11,Petal.Length,Sepal.Width,0.052136,regression,True,mean absolute error,0.330667,0.313427,DecisionTreeRegressor()
12,Petal.Length,Petal.Length,1.000000,predict_itself,True,None,0.000000,1.000000,None
13,Petal.Length,Petal.Width,0.744945,regression,True,mean absolute error,0.644667,0.164425,DecisionTreeRegressor()
14,Petal.Length,Species,0.884812,classification,True,weighted F1,0.353333,0.925512,DecisionTreeClassifier()
15,Petal.Width,Sepal.Length,0.383911,regression,True,mean absolute error,0.684667,0.421816,DecisionTreeRegressor()
16,Petal.Width,Sepal.Width,0.254616,regression,True,mean absolute error,0.330667,0.246474,DecisionTreeRegressor()
17,Petal.Width,Petal.Length,0.798274,regression,True,mean absolute error,1.488667,0.300302,DecisionTreeRegressor()
18,Petal.Width,Petal.Width,1.000000,predict_itself,True,None,0.000000,1.000000,None
19,Petal.Width,Species,0.927652,classification,True,weighted F1,0.353333,0.953215,DecisionTreeClassifier()
20,Species,Sepal.Length,0.409634,regression,True,mean absolute error,0.684667,0.404204,DecisionTreeRegressor()
21,Species,Sepal.Width,0.194307,regression,True,mean absolute error,0.330667,0.266416,DecisionTreeRegressor()
22,Species,Petal.Length,0.785393,regression,True,mean absolute error,1.488667,0.319479,DecisionTreeRegressor()
23,Species,Petal.Width,0.755749,regression,True,mean absolute error,0.644667,0.157460,DecisionTreeRegressor()
24,Species,Species,1.000000,predict_itself,True,None,0.000000,1.000000,None